export const productsCart = [
    {
        id: 1,
        image: '../assets/images/productcart/productcart1.jpg',
        name: 'LG Smart TV 55UP',
        brand: 'LG',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 199,
    },
    {
        id: 2,
        image: '../assets/images/productcart/productcart2.png',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 2,
            name: 'Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.4,
        reviews: 170,
    },
    {
        id: 3,
        image: '../assets/images/productcart/productcart3.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 3.5,
        reviews: 98,
    },
    {
        id: 4,
        image: '../assets/images/productcart/productcart4.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 2,
            name: 'Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 5,
        reviews: 185,
    },
    {
        id: 5,
        image: '../assets/images/productcart/productcart5.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4,
        reviews: 201,
    },
    {
        id: 6,
        image: '../assets/images/productcart/productcart6.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.2,
        reviews: 245,
    },
    {
        id: 7,
        image: '../assets/images/productcart/productcart7.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 57,
    },
    {
        id: 8,
        image: '../assets/images/productcart/productcart8.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 98,
    },
    {
        id: 9,
        image: '../assets/images/productcart/productcart7.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 57,
    },
    {
        id: 10,
        image: '../assets/images/productcart/productcart8.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 98,
    },
];

export const promotioncarts = [
    {
        id: 1,
        image: '../assets/images/promotion/promotioncart1.jpeg',
        name: 'LG Smart TV 55UP',
        brand: 'LG',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 199,
    },
    {
        id: 2,
        image: '../assets/images/promotion/promotioncart2.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.4,
        reviews: 170,
    },
    {
        id: 3,
        image: '../assets/images/promotion/promotioncart3.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 3.5,
        reviews: 98,
    },
    {
        id: 4,
        image: '../assets/images/promotion/promotioncart4.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 5,
        reviews: 185,
    },
    {
        id: 5,
        image: '../assets/images/promotion/promotioncart5.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4,
        reviews: 201,
    },
    {
        id: 6,
        image: '../assets/images/promotion/promotioncart6.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.2,
        reviews: 245,
    },
    {
        id: 7,
        image: '../assets/images/promotion/promotioncart7.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 57,
    },
    {
        id: 8,
        image: '../assets/images/promotion/promotioncart8.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 98,
    },
];

export const trendings = [
    {
        id: 1,
        image: '../assets/images/trending/trending1.png',
        name: 'LG Smart TV 55UP',
        brand: 'LG',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
            desc: 'Bao phí 1.3 triệu',
        },
        price: 990,
        rate: 4.5,
        reviews: 199,
    },
    {
        id: 2,
        image: '../assets/images/trending/trending2.png',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 30,
            desc: 'Giảm đến 30%',
        },
        price: 990,
        rate: 4.4,
        reviews: 170,
    },
    {
        id: 3,
        image: '../assets/images/trending/trending3.png',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 20,
            desc: 'Giảm đến 20%',
        },
        price: 990,
        rate: 3.5,
        reviews: 98,
    },
    {
        id: 4,
        image: '../assets/images/trending/trending4.png',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 20,
            desc: 'Giảm đến 20%',
        },
        price: 990,
        rate: 5,
        reviews: 185,
    },
];

export const featurecategory = [
    {
        id: 1,
        image: '../assets/images/promotion/promotioncart1.jpeg',
        name: 'LG Smart TV 55UP',
        brand: 'LG',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 199,
    },
    {
        id: 2,
        image: '../assets/images/promotion/promotioncart2.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.4,
        reviews: 170,
    },
    {
        id: 3,
        image: '../assets/images/promotion/promotioncart3.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 3.5,
        reviews: 98,
    },
    {
        id: 4,
        image: '../assets/images/promotion/promotioncart4.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 5,
        reviews: 185,
    },
    {
        id: 5,
        image: '../assets/images/promotion/promotioncart5.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4,
        reviews: 201,
    },
    {
        id: 6,
        image: '../assets/images/promotion/promotioncart6.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.2,
        reviews: 245,
    },
    {
        id: 7,
        image: '../assets/images/promotion/promotioncart7.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 57,
    },
    {
        id: 8,
        image: '../assets/images/promotion/promotioncart8.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 98,
    },
    {
        id: 1,
        image: '../assets/images/promotion/promotioncart1.jpeg',
        name: 'LG Smart TV 55UP',
        brand: 'LG',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 199,
    },
    {
        id: 2,
        image: '../assets/images/promotion/promotioncart2.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.4,
        reviews: 170,
    },
    {
        id: 3,
        image: '../assets/images/promotion/promotioncart3.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 3.5,
        reviews: 98,
    },
    {
        id: 4,
        image: '../assets/images/promotion/promotioncart4.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/discounticon.png',
            discountpercent: 20,
        },
        price: 990,
        rate: 5,
        reviews: 185,
    },
    {
        id: 5,
        image: '../assets/images/promotion/promotioncart5.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4,
        reviews: 201,
    },
    {
        id: 6,
        image: '../assets/images/promotion/promotioncart6.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.2,
        reviews: 245,
    },
    {
        id: 7,
        image: '../assets/images/promotion/promotioncart7.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 57,
    },
    {
        id: 8,
        image: '../assets/images/promotion/promotioncart8.jpg',
        name: 'Quạt treo Midea FW40 7JR',
        brand: 'Media',
        promotion: {
            id: 1,
            name: 'Sinh Nhật Giảm Giá Sốc',
            icon: '../assets/images/icon/birthdayicon.png',
            discountpercent: 30,
        },
        price: 990,
        rate: 4.5,
        reviews: 98,
    },
];

export const singleProduct = {
    id: 1,
    image: [
        { id: 1, url: '../assets/images/promotion/promotioncart8.jpg' },
        { id: 2, url: '../assets/images/promotion/promotioncart7.jpg' },
        { id: 3, url: '../assets/images/promotion/promotioncart6.jpg' },
        { id: 4, url: '../assets/images/promotion/promotioncart8.jpg' },
        { id: 5, url: '../assets/images/promotion/promotioncart7.jpg' },
        { id: 6, url: '../assets/images/promotion/promotioncart6.jpg' },
    ],
    name: 'LG Smart TV 55UP',
    brand: 'LG',
    promotion: {
        id: 1,
        name: 'Sinh Nhật Giảm Giá Sốc',
        icon: '../assets/images/icon/birthdayicon.png',
        discountpercent: 30,
    },
    price: [{ id: 1, watage: [20, 30, 40] }],
    rate: 4.5,
    reviews: 199,
};
